### ISSUE TITLE
StandardBundles may need to be preserved.

### ISSUE THREAD

**Issue by gdlcf88** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#1]
![image](https://user-images.githubusercontent.com/30018771/76779006-ab758980-67e5-11ea-9b16-eb805c3ec585.png)

I configure the global bundles in my own module, if Stisla does not use the global bundles, my custom configurations will be invalid.

https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/blob/bf9c0a2744f772321a72550dc0fd963b83529f87/src/AbpAspNetCoreMvcUIStislaThemeModule.cs#L53-L72

Maybe configure `StandardBundles.Styles.Global` and `StandardBundles.Scripts.Global` is a good way:

```
    public class StislaThemeGlobalScriptContributor : BundleContributor
    {
        public override void ConfigureBundle(BundleConfigurationContext context)
        {
            context.Files.Remove( ... );
            // Add more.
        }
    }
```

**Comment by realLiangshiwei** [comment]
Fixed by :https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/0c1c72902948f6278bb42057389626c176b1f1c3
