### ISSUE TITLE
Menu elementId be urlencode

### ISSUE THREAD

**Issue by JadynWong** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#18]
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/blob/4e082387945f082e8802c91546e66e59c5964966/src/Themes/Stisla/Components/Menu/Default.cshtml#L10-L21

https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/blob/4e082387945f082e8802c91546e66e59c5964966/src/Themes/Stisla/Components/Menu/_MenuItem.cshtml#L7-L19

The variable `elementId` will be urlencode at razor page.

Unless use `Html.Raw`  method to render raw content.

**Comment by realLiangshiwei** [comment]
Sorry,I just saw this issue. I didn't understand your question, can you explain it in detail? Thanks.

**Comment by JadynWong** [comment]
The variable `elementId` will be add html escape double quotation`&quot;`.
![image](https://user-images.githubusercontent.com/13699353/85935039-48d07580-b91e-11ea-9c42-14f2e035fdba.png)
![image](https://user-images.githubusercontent.com/13699353/85935044-5c7bdc00-b91e-11ea-8fd8-2d1f87803d2a.png)

**Comment by realLiangshiwei** [comment]
You are right, I will fix this.

**Comment by realLiangshiwei** [comment]
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/a9a191a312def6db8ebae5594aa5349278a15c1a
