### ISSUE TITLE
Tenant select button in the login page does not work.

### ISSUE THREAD

**Issue by gdlcf88** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#2]
Click it, but it doesn't work. My browser version is Edge 80.0.361.66.

**Comment by realLiangshiwei** [comment]
Fixed by :https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/0c1c72902948f6278bb42057389626c176b1f1c3
