### ISSUE TITLE
不能在abp 4.3版本上使用 请帮忙看一下为什么捏

### ISSUE THREAD

**Issue by Qianzujin** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#22]
不能在abp 4.3版本上使用 请帮忙看一下为什么捏

**Comment by realLiangshiwei** [comment]
更新了 https://www.nuget.org/packages/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/
