### ISSUE TITLE
how to Deploy This project IIS?

### ISSUE THREAD

**Issue by SELVAGANAPATHIARUMUGAMG** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#28]
IN This project working properly in localhost but still hosting the IIS that time does not work Css file

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AntDesignUI/commit/dae169c536ace6bf4420ef9fe7dc2d7c3a2371dc

**Comment by realLiangshiwei** [comment]
How to reproduce it?
