### ISSUE TITLE
点击左侧菜单收缩时，Table表头发生错位

### ISSUE THREAD

**Issue by weiwxg** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#30]
![1653710122(1)](https://user-images.githubusercontent.com/24971860/170808888-1536dcd2-8c32-4cdc-83bb-c816c5451a9e.png)

错位后，点击对应的表头就会恢复正常

另外，表格的footer部分选择每页显示记录数的下拉样式有点怪异

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/b08a89355d8bea3d47ccb64358a91a2af2049a80
