### ISSUE TITLE
Template issue : An unhandled exception occurred while processing the request. when accessing /Identity/Users

### ISSUE THREAD

**Issue by rlabrador** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#33]
Hello.
Ive deployed a standard project abp new <MyProjectName>.
Did what you sudgest replacing the AbpAspNetCoreMvcUiLeptonXLiteThemeModule and LeptonXLiteThemeBundles.Styles.Global
by AbpAspNetCoreMvcUiStislaThemeModule and StislaThemeBundles.Styles.Global.
and get this issue testing the module with Identity.
Thanks.

![Screen Shot 01-31-23 at 11 02 PM 001](https://user-images.githubusercontent.com/7700620/215975864-ccbe1a6a-8ee4-4334-bd86-38a4cecff610.PNG)

**Comment by tynorton** [comment]
Same issue here

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/c7f93defd3fb16b8d132e5392f6f0a3ac5aa451e
