### ISSUE TITLE
升级到2.3后报未在布局文件中定义content_toolbar错误

### ISSUE THREAD

**Issue by J6666** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#34]
The following sections have been defined but have not been rendered by the page at '/Themes/Stisla/Layouts/Application.cshtml': 'content_toolbar'.

**Comment by realLiangshiwei** [comment]
I will check it

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/c7f93defd3fb16b8d132e5392f6f0a3ac5aa451e
