### ISSUE TITLE
Static files are loaded repeatedly.

### ISSUE THREAD

**Issue by gdlcf88** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#4]
For example:

![image](https://user-images.githubusercontent.com/30018771/76827424-ba961f00-6859-11ea-854e-19e201a31e9e.png)

**Comment by realLiangshiwei** [comment]
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/b22f68007bd371d1e8509f89cba58eb7999893df
