### ISSUE TITLE
Language switch may need a icon in small width browser.

### ISSUE THREAD

**Issue by gdlcf88** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#5]
![image](https://user-images.githubusercontent.com/30018771/76827683-617abb00-685a-11ea-8185-f3a060af47c9.png)

Or we can do the same as the baisc template: move other menus into the user menu.

**Comment by realLiangshiwei** [comment]
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/b22f68007bd371d1e8509f89cba58eb7999893df
