### ISSUE TITLE
Index page buttons column optimization suggestion

### ISSUE THREAD

**Issue by gdlcf88** [liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla#6]
![image](https://user-images.githubusercontent.com/30018771/76828324-a81ce500-685b-11ea-9ac5-b446ab3eafa8.png)

![image](https://user-images.githubusercontent.com/30018771/76828385-c7b40d80-685b-11ea-8117-2d11b6181d3c.png)

Maybe we can move the buttons column to right side.

**Comment by realLiangshiwei** [comment]
https://github.com/liangshiw/Lsw.Abp.AspNetCore.Mvc.UI.Theme.Stisla/commit/db9e85c4cdde1d89add6351d1769116fbbde0290
